=== yuryshahov/YuryShahov/YuryShahov/Task3/bank.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.by/bank"
        xmlns:tns="http://www.epam.by/bank"
        elementFormDefault="qualified">
  <element name="account" type="tns:Account" abstract="true"/>
  <element name="deposite" type="tns:Deposite" substitutionGroup="tns:account"/>
  <element name="credit" type="tns:Credit" substitutionGroup="tns:account"/>
  <element name="bank">
    <complexType>
      <sequence>
        <element ref="tns:account" minOccurs="0" maxOccurs="unbounded"/>
      </sequence>
    </complexType>
  </element>
  <complexType name="Credit">
    <complexContent>
      <extension base="tns:Account">
        <sequence>
          <element name="credit-type" type="tns:CreditType"/>
          <element name="dept" type="double"/>
        </sequence>
        <attribute name="id" use="required" type="ID"/>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="Deposite">
    <complexContent>
      <extension base="tns:Account">
        <sequence>
          <element name="deposite-type" type="tns:DepositeType"/>
          <element name="amount" type="double"/>
        </sequence>
        <attribute name="id" use="required" type="tns:Id"/>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="Account">
    <sequence>
      <element name="name" type="string"/>
      <element name="product-name" type="string"/>
      <element name="country" type="string"/>
      <element name="person" type="tns:Person"/>
      <element name="account-id" type="unsignedLong"/>
      <element name="currency" type="tns:Currency"/>
      <element name="allperiod" type="tns:AllPeriod"/>
    </sequence>
  </complexType>
  <complexType name="Person">
    <sequence>
      <element name="first-name" type="string"/>
      <element name="last-name" type="string"/>
      <element name="telephone" type="tns:Telephone"/>
    </sequence>
  </complexType>
  <complexType name="AllPeriod">
    <sequence>
      <element name="period" type="tns:Period" minOccurs="1" maxOccurs="unbounded"/>
    </sequence>
  </complexType>
  <complexType name="Period">
    <sequence>
      <element name="profitability" type="double"/>
      <element name="time-type" type="tns:TimeType" default="month"/>
      <element name="time-min" type="unsignedInt" minOccurs="0" maxOccurs="unbounded"/>
      <element name="time-max" type="unsignedInt" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
  </complexType>
  <simpleType name="Id">
    <restriction base="ID">
      <pattern value="^[0-9]*$"/>
    </restriction>
  </simpleType>
  <simpleType name="Telephone">
    <restriction base="string">
      <pattern value="^[0-9, ]*$"/>
    </restriction>
  </simpleType>
  <simpleType name="DepositeType">
    <restriction base="string">
      <pattern value="до востребования|срочный|расчетный|накопительный|сберегательный|металлический"/>
    </restriction>
  </simpleType>
  <simpleType name="CreditType">
    <restriction base="string">
      <pattern value="экспресс|классический"/>
    </restriction>
  </simpleType>
  <simpleType name="TimeType">
    <restriction base="string">
      <pattern value="no|day|month|year"/>
    </restriction>
  </simpleType>
  <simpleType name="Currency">
    <restriction base="string">
      <enumeration value="USD"/>
      <enumeration value="EUR"/>
      <enumeration value="RUB"/>
      <enumeration value="BYR"/>
      <length value="3"/>
    </restriction>
  </simpleType>
</schema>

=== yuryshahov/YuryShahov/YuryShahov/Task3/bank.xml
<?xml version="1.0" encoding="UTF-8"?>
<bank xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.epam.by/bank"
      xsi:schemaLocation="http://www.epam.by/bank  bank.xsd">
	<deposite id="x1">
    <name>Банк БелВЭБ</name>
    <product-name>Золотое время</product-name>
    <country>Беларусь</country>
    <person>
      <first-name>Иван</first-name>
      <last-name>Иванов</last-name>
      <telephone>80293245345</telephone>
    </person>
		<account-id>234234325563</account-id>
    <currency>BYR</currency>
    <allperiod>
			<period>
				<profitability>34</profitability>
				<time-type>no</time-type>
				<time-min>0</time-min>
				<time-max>0</time-max>
			</period>
		</allperiod>
    <deposite-type>срочный</deposite-type>
    <amount>234653482335</amount>
	</deposite>
  <credit id="x2">
    <name>Банк БелВЭБ</name>
    <product-name>Портребительский</product-name>
    <country>Беларусь</country>
    <person>
      <first-name>Иван</first-name>
      <last-name>Иванов</last-name>
      <telephone>80293245345</telephone>
    </person>
    <account-id>234343554635</account-id>
    <currency>BYR</currency>
    <allperiod>
      <period>
        <profitability>86</profitability>
        <time-type>month</time-type>
        <time-min>4</time-min>
        <time-max>6</time-max>
      </period>
    </allperiod>
    <credit-type>экспресс</credit-type>
    <dept>234423555566</dept>
  </credit>
	<deposite id="x3">
		<name>Идея Банк</name>
		<product-name>Заботливый</product-name>
		<country>Беларусь</country>
    <person>
      <first-name>Петр</first-name>
      <last-name>Петров</last-name>
      <telephone>80292432553</telephone>
    </person>
		<account-id>323434325533</account-id>
		<currency>BYR</currency>
    <allperiod>
      <period>
				<profitability>33.5</profitability>
				<time-type>month</time-type>
				<time-min>0</time-min>
				<time-max>6</time-max>
			</period>
      <period>
				<profitability>25.5</profitability>
				<time-type>month</time-type>
				<time-min>7</time-min>
				<time-max>18</time-max>
			</period>
		</allperiod>
    <deposite-type>срочный</deposite-type>
    <amount>71234687135</amount>
	</deposite>
	<deposite id="x4">
		<name>Банк ВТБ</name>
		<product-name>Капитал</product-name>
		<country>Беларусь</country>
		<person>
			<first-name>Сидр</first-name>
			<last-name>Сидоров</last-name>
      <telephone>80293849183</telephone>
		</person>
		<account-id>423434352134</account-id>
		<currency>BYR</currency>
    <allperiod>
			<period>
				<profitability>33</profitability>
				<time-type>month</time-type>
				<time-min>5</time-min>
				<time-max>24</time-max>
			</period>
		</allperiod>
    <deposite-type>срочный</deposite-type>
    <amount>285724554435</amount>
	</deposite>
	<deposite id="x5">
		<name>Банк ВТБ</name>
		<product-name>Дорогой</product-name>
		<country>Беларусь</country>
		<person>
			<first-name>Иван</first-name>
			<last-name>Сидоров</last-name>
      <telephone>80339382474</telephone>
		</person>
		<account-id>123456789012</account-id>
		<currency>BYR</currency>
    <allperiod>
			<period>
				<profitability>33</profitability>
				<time-type>month</time-type>
				<time-min>3</time-min>
				<time-max>12</time-max>
			</period>
		</allperiod>
    <deposite-type>срочный</deposite-type>
    <amount>34563479658</amount>
	</deposite>
	<deposite id="x6">
		<name>Банк БелВЭБ</name>
		<product-name>Персона</product-name>
		<country>Беларусь</country>
		<person>
			<first-name>Сергей</first-name>
			<last-name>Петрович</last-name>
      <telephone>80449114372</telephone>
		</person>
		<account-id>435435464646</account-id>
		<currency>USD</currency>
    <allperiod>
			<period>
				<profitability>4.5</profitability>
				<time-type>month</time-type>
				<time-min>1</time-min>
				<time-max>3</time-max>
			</period>
      <period>
        <profitability>5.6</profitability>
        <time-type>month</time-type>
        <time-min>3</time-min>
        <time-max>6</time-max>
      </period>
			<period>
				<profitability>6.2</profitability>
				<time-type>month</time-type>
				<time-min>6</time-min>
				<time-max>12</time-max>
			</period>
			<period>
				<profitability>6.5</profitability>
				<time-type>month</time-type>
				<time-min>12</time-min>
				<time-max>24</time-max>
			</period>
		</allperiod>
    <deposite-type>накопительный</deposite-type>
    <amount>475643</amount>
	</deposite>
  <credit id="x7">
    <name>Портребительский</name>
    <product-name>Золотое время</product-name>
    <country>Беларусь</country>
    <person>
      <first-name>Иван</first-name>
      <last-name>Иванов</last-name>
      <telephone>80293245345</telephone>
    </person>
    <account-id>723434243218</account-id>
    <currency>BYR</currency>
    <allperiod>
      <period>
        <profitability>86</profitability>
        <time-type>month</time-type>
        <time-min>4</time-min>
        <time-max>6</time-max>
      </period>
    </allperiod>
    <credit-type>экспресс</credit-type>
    <dept>234423555566</dept>
  </credit>
</bank>
